spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      generate-ddl: true
      ddl-auto: create
server:
  servlet:
    contextPath: /api-produtos/
  port: 8080